"""empty message

Revision ID: b58604cc7f41
Revises: 
Create Date: 2021-11-20 15:50:36.185577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58604cc7f41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=60), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('jobseekers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('education_title', sa.String(), nullable=True),
    sa.Column('education_date_start', sa.DateTime(), nullable=True),
    sa.Column('education_date_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobseekers_id', sa.Integer(), nullable=False),
    sa.Column('companies_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['companies_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['jobseekers_id'], ['jobseekers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('jobseekers_id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['jobseekers_id'], ['jobseekers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companies_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['companies_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('chats_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chats_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('openings_channels',
    sa.Column('channels_id', sa.Integer(), nullable=True),
    sa.Column('openings_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channels_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['openings_id'], ['openings.id'], )
    )
    op.create_table('swipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobseekers_id', sa.Integer(), nullable=False),
    sa.Column('openings_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('swiped_right', sa.Boolean(), nullable=False),
    sa.Column('super_swipe', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['jobseekers_id'], ['jobseekers.id'], ),
    sa.ForeignKeyConstraint(['openings_id'], ['openings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swipes')
    op.drop_table('openings_channels')
    op.drop_table('messages')
    op.drop_table('openings')
    op.drop_table('experiences')
    op.drop_table('chats')
    op.drop_table('jobseekers')
    op.drop_table('companies')
    op.drop_table('channels')
    # ### end Alembic commands ###
